[package]
name = "apz-pzpi-21-11-milennyi-ivan-task3"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
json = "0.12.4"
rand = "0.8.5"
reqwest = { version = "0.12.4", features = ["json"] }
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
